# Generated by Django 6.1.1 on 2026-10-03 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catergory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='recurringexpense',
            old_name='frequncy',
            new_name='frequency',
        ),
    ]
