# Generated by Django 6.1.1 on 2026-10-03 21:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_catergory_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catergory',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='title',
            new_name='tittle',
        ),
        migrations.RenameField(
            model_name='recurringexpense',
            old_name='frequency',
            new_name='frequncy',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='total_expenses',
        ),
    ]
