# Generated by Django 6.1.1 on 2026-10-03 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_category_catergory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='tittle',
            new_name='title',
        ),
    ]
